spring:
  profiles: dev #开发环境
  application:
    name: eurka-server
server:
  port: 7001
eureka:
  instance: 
   # hostname: localhost #eureka服务端的实例名称   单机模式   
   hostname: eurka01.com
   instance-id: eurka-service01  #集群配置 这里要不同
   prefer-ip-address: true   # 访问路径可以ip 显示
  client:
    register-with-eureka: true #false表示不向注册中心注册自己#集群时 要设置为true
    fetch-registry: true #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务   #集群时 要设置为true
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址单机版胚子
      defaultZone: http://eurka02.com:7002/eureka,http://eurka03.com:7003/eureka   #集群配置
info:   #追加微服务 信息 
  app.name: eurka-server
  company.name: www.zjx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$      
        
        
---
spring:
  profiles: test #开发环境
  application:
    name: eurka-server
server:
  port: 7001
eureka:
  instance: 
   # hostname: localhost #eureka服务端的实例名称   单机模式   
   hostname: eurka01.com
   instance-id: eurka-service01  #集群配置 这里要不同
   prefer-ip-address: true   # 访问路径可以ip 显示
  client:
    register-with-eureka: true #false表示不向注册中心注册自己#集群时 要设置为true
    fetch-registry: true #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务   #集群时 要设置为true
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址单机版胚子
      defaultZone: http://eurka02.com:7002/eureka,http://eurka03.com:7003/eureka   #集群配置
info:   #追加微服务 信息 
  app.name: eurka-server
  company.name: www.zjx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$      
        